# we need to use this hacky workaround because github actions don't support using docker containers from private repositories
# if we just do docker://bla-bla, then actions will try to pull it before all the steps, ahead of authorisation to gcloud
# but it doesn't do it in an internal action
# see more here: https://github.community/t/github-actions-new-pulling-from-private-docker-repositories/16089

name: hacky action to make the use of docker container
inputs:
  token:
    description: 'The GITHUB_TOKEN value'
    required: true
  type:
    description: 'main vs. branch'
    required: true
  verbose:
    description: 'Enable additional logging'
runs:
  using: 'docker'
  image: 'docker://asia.gcr.io/igneous-ethos-277602/insights-action:latest'
