name: ci

on:
  push:
    branches: [ master ]

env:
  isCI: true
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      # Configures auth for the private npm repositories.
      # NPM auth key should be passed as NODE_AUTH_TOKEN env to the command that needs authorisation
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: yarn install
        run: yarn install --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: yarn ts
        run: yarn ts

      # ===================
      # ==== gelato.fm ====
      # ===================

      - name: "**** start gelato.fm ****"
        run: echo yey!

      # set up the google cloud cli
      - name: set up google cloud cli
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '285.0.0'
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true

      - name: auth at google cloud
        run: gcloud auth configure-docker

      - name: pull docker image
        run: |
          docker pull "asia.gcr.io/igneous-ethos-277602/insights-action:latest"

        # we need to use this hacky workaround because github actions don't support using docker containers from private repositories
        # if we just do docker://bla-bla, then actions will try to pull it before all the steps, ahead of authorisation to gcloud
        # but it doesn't do it in an internal action
        # see more here: https://github.community/t/github-actions-new-pulling-from-private-docker-repositories/16089
      - name: gelato.fm build and deploy
        uses: ./.github/workflows/hacky-gfm-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          type: main
        env:
          FORCE_COLOR: 2 # needed to get chalk to work; see https://github.com/chalk/supports-color/issues/106
