name: ci
'on':
  push:
    branches:
      - master
env:
  isCI: true
  GIT_TOKEN: '${{ secrets.GIT_TOKEN }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: 'https://npm.pkg.github.com'
      - name: yarn install
        run: 'yarn install --registry=https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: '${{ secrets.GIT_TOKEN }}'
      - name: run typescript
        run: yarn ts
      - name: run build
        run: yarn build
